[package]
name = "diesel_minmal_repro_left_join_count"
version = "0.1.0"
authors = ["Luca Casonato <lucacasonato@yahoo.com>"]
edition = "2021"

[dependencies]
diesel = { version = "2", features = ["postgres"] }
dotenv = "0.15.0"


